spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/games?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123

server:
  port: 1010


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
